# Remove wrong images from the csv produced by VIA tool and save into the proper format

In [41]:
import os
import pandas as pd 

PATH = '../../data/dogfacenet/aligned/'
df = pd.read_csv(PATH+'labels/via_region_data(17)2.csv')
df.head()

,filename,file_size,file_attributes,region_count,region_id,region_shape_attributes,region_attributes
0,272100.272100.jpg,28889,{},3,0,"{""name"":""point"",""cx"":122,""cy"":175}",{}
1,272100.272100.jpg,28889,{},3,1,"{""name"":""point"",""cx"":230,""cy"":185}",{}
2,272100.272100.jpg,28889,{},3,2,"{""name"":""point"",""cx"":149,""cy"":319}",{}
3,272100.272100_0.jpg,30813,{},3,0,"{""name"":""point"",""cx"":196,""cy"":161}",{}
4,272100.272100_0.jpg,30813,{},3,1,"{""name"":""point"",""cx"":287,""cy"":175}",{}

In [42]:
df2 = df[df.region_count == 3]

In [43]:
len(df2)/3

8698.0

In [44]:
df3 = df2[['filename','region_shape_attributes']]

In [5]:
df3.head()

              filename             region_shape_attributes
0    272100.272100.jpg  {"name":"point","cx":122,"cy":175}
1    272100.272100.jpg  {"name":"point","cx":230,"cy":185}
2    272100.272100.jpg  {"name":"point","cx":149,"cy":319}
3  272100.272100_0.jpg  {"name":"point","cx":196,"cy":161}
4  272100.272100_0.jpg  {"name":"point","cx":287,"cy":175}

In [45]:
from ast import literal_eval
df3['region_shape_attributes'] = df3['region_shape_attributes'].apply(literal_eval)

c:\users\guillaume\anaconda3\lib\site-packages\ipykernel_launcher.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy

In [46]:
df3.head()

              filename                  region_shape_attributes
0    272100.272100.jpg  {'name': 'point', 'cx': 122, 'cy': 175}
1    272100.272100.jpg  {'name': 'point', 'cx': 230, 'cy': 185}
2    272100.272100.jpg  {'name': 'point', 'cx': 149, 'cy': 319}
3  272100.272100_0.jpg  {'name': 'point', 'cx': 196, 'cy': 161}
4  272100.272100_0.jpg  {'name': 'point', 'cx': 287, 'cy': 175}

In [47]:
df3['id'] = [i for i in range(len(df3))]

c:\users\guillaume\anaconda3\lib\site-packages\ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  """Entry point for launching an IPython kernel.

In [48]:
df3 = df3.set_index('id')

In [49]:
dic = df3['region_shape_attributes'][0]
dic

{'cx': 122, 'cy': 175, 'name': 'point'}

In [50]:
dic['cx']

122

In [51]:
df4 = pd.DataFrame(index=[i for i in range(len(df3)//3)],columns=['filename','lex','ley','rex','rey','nox','noy'])

In [52]:
df4['filename']=[df3['filename'][i] for i in range(0,len(df3),3)]
df4['lex'] = [df3['region_shape_attributes'][i]['cx'] for i in range(0,len(df3),3)]
df4['ley'] = [df3['region_shape_attributes'][i]['cy'] for i in range(0,len(df3),3)]
df4['rex'] = [df3['region_shape_attributes'][i]['cx'] for i in range(1,len(df3),3)]
df4['rey'] = [df3['region_shape_attributes'][i]['cy'] for i in range(1,len(df3),3)]
df4['nox'] = [df3['region_shape_attributes'][i]['cx'] for i in range(2,len(df3),3)]
df4['noy'] = [df3['region_shape_attributes'][i]['cy'] for i in range(2,len(df3),3)]

In [53]:
df3

                    filename                  region_shape_attributes
id
0          272100.272100.jpg  {'name': 'point', 'cx': 122, 'cy': 175}
1          272100.272100.jpg  {'name': 'point', 'cx': 230, 'cy': 185}
2          272100.272100.jpg  {'name': 'point', 'cx': 149, 'cy': 319}
3        272100.272100_0.jpg  {'name': 'point', 'cx': 196, 'cy': 161}
4        272100.272100_0.jpg  {'name': 'point', 'cx': 287, 'cy': 175}
5        272100.272100_0.jpg  {'name': 'point', 'cx': 172, 'cy': 296}
6        272100.272100_1.jpg  {'name': 'point', 'cx': 404, 'cy': 125}
7        272100.272100_1.jpg  {'name': 'point', 'cx': 447, 'cy': 116}
8        272100.272100_1.jpg  {'name': 'point', 'cx': 441, 'cy': 177}
9        272100.272100_2.jpg   {'name': 'point', 'cx': 100, 'cy': 95}
10       272100.272100_2.jpg  {'name': 'point', 'cx': 155, 'cy': 103}
11       272100.272100_2.jpg  {'name': 'point', 'cx': 113, 'cy': 168}
12       272100.272100_4.jpg   {'name': 'point', 'cx': 158, 'cy': 75}
13       272100.272100_4.jpg   {'name': 'point', 'cx': 215, 'cy': 79}
14       272100.272100_4.jpg  {'name': 'point', 'cx': 177, 'cy': 139}
15       272100.272100_5.jpg   {'name': 'point', 'cx': 137, 'cy': 77}
16       272100.272100_5.jpg   {'name': 'point', 'cx': 186, 'cy': 80}
17       272100.272100_5.jpg  {'name': 'point', 'cx': 155, 'cy': 138}
18         272774.272774.jpg   {'name': 'point', 'cx': 167, 'cy': 97}
19         272774.272774.jpg   {'name': 'point', 'cx': 244, 'cy': 94}
20         272774.272774.jpg  {'name': 'point', 'cx': 187, 'cy': 157}
21      272774.272774_0.jpeg   {'name': 'point', 'cx': 233, 'cy': 81}
22      272774.272774_0.jpeg   {'name': 'point', 'cx': 269, 'cy': 81}
23      272774.272774_0.jpeg  {'name': 'point', 'cx': 240, 'cy': 128}
24       272774.272774_0.jpg  {'name': 'point', 'cx': 263, 'cy': 145}
25       272774.272774_0.jpg  {'name': 'point', 'cx': 323, 'cy': 141}
26       272774.272774_0.jpg  {'name': 'point', 'cx': 337, 'cy': 208}
27       272774.272774_1.jpg   {'name': 'point', 'cx': 173, 'cy': 60}
28       272774.272774_1.jpg   {'name': 'point', 'cx': 207, 'cy': 61}
29       272774.272774_1.jpg   {'name': 'point', 'cx': 177, 'cy': 87}
...                      ...                                      ...
26064      Zsu-2.Zsu-2-2.jpg  {'name': 'point', 'cx': 340, 'cy': 263}
26065      Zsu-2.Zsu-2-2.jpg  {'name': 'point', 'cx': 422, 'cy': 255}
26066      Zsu-2.Zsu-2-2.jpg  {'name': 'point', 'cx': 404, 'cy': 375}
26067      Zsu-2.Zsu-2-3.jpg  {'name': 'point', 'cx': 172, 'cy': 219}
26068      Zsu-2.Zsu-2-3.jpg  {'name': 'point', 'cx': 263, 'cy': 220}
26069      Zsu-2.Zsu-2-3.jpg  {'name': 'point', 'cx': 192, 'cy': 351}
26070      Zsu-2.Zsu-2-4.jpg  {'name': 'point', 'cx': 231, 'cy': 202}
26071      Zsu-2.Zsu-2-4.jpg  {'name': 'point', 'cx': 350, 'cy': 203}
26072      Zsu-2.Zsu-2-4.jpg  {'name': 'point', 'cx': 294, 'cy': 326}
26073      Zsu-2.Zsu-2-5.jpg  {'name': 'point', 'cx': 192, 'cy': 138}
26074      Zsu-2.Zsu-2-5.jpg  {'name': 'point', 'cx': 255, 'cy': 135}
26075      Zsu-2.Zsu-2-5.jpg  {'name': 'point', 'cx': 260, 'cy': 199}
26076  Zumba-2.Zumba-2-2.jpg  {'name': 'point', 'cx': 255, 'cy': 274}
26077  Zumba-2.Zumba-2-2.jpg  {'name': 'point', 'cx': 404, 'cy': 267}
26078  Zumba-2.Zumba-2-2.jpg  {'name': 'point', 'cx': 352, 'cy': 478}
26079  Zumba-2.Zumba-2-3.jpg  {'name': 'point', 'cx': 265, 'cy': 299}
26080  Zumba-2.Zumba-2-3.jpg  {'name': 'point', 'cx': 374, 'cy': 207}
26081  Zumba-2.Zumba-2-3.jpg  {'name': 'point', 'cx': 446, 'cy': 401}
26082  Zumba-2.Zumba-2-4.jpg  {'name': 'point', 'cx': 149, 'cy': 227}
26083  Zumba-2.Zumba-2-4.jpg  {'name': 'point', 'cx': 213, 'cy': 222}
26084  Zumba-2.Zumba-2-4.jpg  {'name': 'point', 'cx': 175, 'cy': 315}
26085  Zumba-2.Zumba-2-5.jpg  {'name': 'point', 'cx': 346, 'cy': 199}
26086  Zumba-2.Zumba-2-5.jpg  {'name': 'point', 'cx': 412, 'cy': 179}
26087  Zumba-2.Zumba-2-5.jpg  {'name': 'point', 'cx': 412, 'cy': 276}
26088  Zumba-2.Zumba-2-6.jpg  {'name': 'point', 'cx': 380, 'cy': 135}
26089  Zumba-2.Zumba-2-6.jpg  {'name': 'point', 'cx': 419, 'cy': 138}
26090  Zumba-2.Zumba-2-6.jpg  {'name': 'point', 'cx': 401, 'cy': 194}
26091  Zumba-2.Zumba-2-9.jpg  {'name': 'point', 'cx': 132, 'cy': 189}
26092  Zumba-2.Zumba-2-9.jpg  {'name': 'point', 'cx': 162, 'cy': 187}
26093  Zumba-2.Zumba-2-9.jpg  {'name': 'point', 'cx': 147, 'cy': 235}

[26094 rows x 2 columns]

In [54]:
df4

                         filename  lex  ley  rex  rey  nox  noy
0               272100.272100.jpg  122  175  230  185  149  319
1             272100.272100_0.jpg  196  161  287  175  172  296
2             272100.272100_1.jpg  404  125  447  116  441  177
3             272100.272100_2.jpg  100   95  155  103  113  168
4             272100.272100_4.jpg  158   75  215   79  177  139
5             272100.272100_5.jpg  137   77  186   80  155  138
6               272774.272774.jpg  167   97  244   94  187  157
7            272774.272774_0.jpeg  233   81  269   81  240  128
8             272774.272774_0.jpg  263  145  323  141  337  208
9             272774.272774_1.jpg  173   60  207   61  177   87
10            272774.272774_2.jpg  263  113  351  111  302  192
11            272774.272774_3.jpg  267  173  301  166  295  194
12             272986.272986.jpeg  237  149  303  153  293  209
13              272986.272986.jpg  261  119  317  114  297  166
14            272986.272986_0.jpg  270  147  321  148  307  209
15            272986.272986_1.jpg  252  157  315  157  257  239
16            272986.272986_2.jpg  239  117  295  123  252  185
17            272986.272986_5.jpg  337  131  363  129  353  160
18            272986.272986_6.jpg  231  138  275  135  248  195
19             274575.274575.jpeg  256  123  335   99  319  165
20              274575.274575.jpg  201  123  287  107  256  155
21           274575.274575_0.jpeg  362   93  397   92  388  122
22            274575.274575_0.jpg  178  116  261  119  199  179
23            274575.274575_1.jpg  225   64  273   59  250   87
24            274575.274575_2.jpg  213  142  267  151  217  193
25            274575.274575_3.jpg  151   79  185   83  155  108
26            274575.274575_4.jpg  274  116  311  120  293  138
27            276562.276562_0.jpg  234   33  273   41  243   53
28            276562.276562_2.jpg  268   93  349  108  293  173
29            276562.276562_3.jpg  220  125  292  137  243  181
...                           ...  ...  ...  ...  ...  ...  ...
8668      Zeusz-11.Zeusz-11-5.jpg  219  184  355  180  273  344
8669      Zeusz-11.Zeusz-11-6.jpg  303  373  410  377  507  539
8670      Zeusz-11.Zeusz-11-7.jpg  223  114  249  113  245  137
8671      Zeusz-11.Zeusz-11-8.jpg  205  256  254  262  221  316
8672        Zorro-5.Zorro-5-1.jpg  398  159  470  148  484  242
8673        Zorro-5.Zorro-5-2.jpg  160  249  329  239  213  420
8674        Zorro-5.Zorro-5-3.jpg  194  175  308  185  214  275
8675        Zorro-5.Zorro-5-4.jpg  245  218  447  227  427  442
8676   Zorro-5.Zorro-5-6.jpeg.jpg  182  372  219  372  198  414
8677        Zorro-5.Zorro-5-7.jpg  314  171  343  170  331  196
8678        Zorro-5.Zorro-5-8.jpg  218  246  309  253  287  290
8679        Zorro-5.Zorro-5-9.jpg  341  302  410  300  428  391
8680  Zorro-5.Zorro-5-10.jpeg.jpg  163  208  234  209  213  297
8681       Zorro-5.Zorro-5-20.jpg  131  299  162  300  140  342
8682        Zotya-3.Zotya-3-1.jpg  121  205  178  199  149  259
8683        Zotya-3.Zotya-3-2.jpg  171  159  254  146  241  232
8684        Zotya-3.Zotya-3-3.jpg  258  190  398  197  347  258
8685        Zotya-3.Zotya-3-4.jpg  235  225  373  224  303  327
8686        Zotya-3.Zotya-3-5.jpg  127  135  182  133  157  170
8687            Zsu-2.Zsu-2-1.jpg  341  204  426  205  392  318
8688            Zsu-2.Zsu-2-2.jpg  340  263  422  255  404  375
8689            Zsu-2.Zsu-2-3.jpg  172  219  263  220  192  351
8690            Zsu-2.Zsu-2-4.jpg  231  202  350  203  294  326
8691            Zsu-2.Zsu-2-5.jpg  192  138  255  135  260  199
8692        Zumba-2.Zumba-2-2.jpg  255  274  404  267  352  478
8693        Zumba-2.Zumba-2-3.jpg  265  299  374  207  446  401
8694        Zumba-2.Zumba-2-4.jpg  149  227  213  222  175  315
8695        Zumba-2.Zumba-2-5.jpg  346  199  412  179  412  276
8696        Zumba-2.Zumba-2-6.jpg  380  135  419  138  401  194
8697        Zumba-2.Zumba-2-9.jpg  132  189  162  187  147  235

[8698 rows x 7 columns]

In [55]:
df4.to_csv(PATH+'labels/reformated_8698.csv')

In [15]:
import shutil

In [39]:
for root,dirs,files in os.walk("../../data/dogfacenet/images/"):
    if len(dirs)==0 and len(files)==0:
        print(root + ' ' + str(len(files)))
         #os.remove(root)
        #shutil.rmtree(root)

In [16]:
from tqdm import tqdm_notebook

In [26]:
PATH_BEF = '../../data/dogfacenet/aligned/before_4'

In [27]:
filenames = os.listdir(PATH_BEF)

In [37]:
foldernames = []
for f in filenames:
    c = 0
    s = f.find('.',0)
    if s < 2:
        s = f.find('.',s+1)
    if not f[:s] in foldernames:
        foldernames += [f[:s]]

foldernames

['180&tit=Wolf',
 '186&tit=Dor',
 '23&tit=San',
 '231&tit=Dorl',
 '24&tit=Tang',
 '26&tit=Shil',
 '272100',
 '272774',
 '272986',
 '273074',
 '273740',
 '274120',
 '274265',
 '274575',
 '276511',
 '276562',
 '276604',
 '277097',
 '277127',
 '277352',
 '280898',
 '283810',
 '284418',
 '288447',
 '289166',
 '29&tit=Jack',
 '290842',
 '293238',
 '293926',
 '296334',
 '296918',
 '297592',
 '298071',
 '30&tit=Bal',
 '302079',
 '304072',
 '304096',
 '309782',
 '31&tit=Bon',
 '312596',
 '314325',
 '314995',
 '318324',
 '322865',
 '323275',
 '332304',
 '332627',
 '332776',
 '334839',
 '336024',
 '336189',
 '336509',
 '338449',
 '339354',
 '339445',
 '343097',
 '343563',
 '343619',
 '344199',
 '344682',
 '345318',
 '345377',
 '345684',
 '347607',
 '348334',
 '348335',
 '349078',
 '349395',
 '349722',
 '353068',
 '354600',
 '354638',
 '355842',
 '356804',
 '358143',
 '359410',
 '359936',
 '360092',
 '360472',
 '360863',
 '360864',
 '361420',
 '361961',
 '362588',
 '363352',
 '363378',
 '364876',
 '364980',
 '367550',
 '368053',
 '368706',
 '368992',
 '369547',
 '369567',
 '369587',
 '369600',
 '369680',
 '370434',
 '370485',
 '370994',
 '371134',
 '371745',
 '372017',
 '372059',
 '372097',
 '372170',
 '372651',
 '372844',
 '372871',
 '373091',
 '373306',
 '373469',
 '373589',
 '373603',
 '373762',
 '374059',
 '374127',
 '374966',
 '375230',
 '375292',
 '375349',
 '376260',
 '376469',
 '376498',
 '377039',
 '377139',
 '377581',
 '378124',
 '378220',
 '378437',
 '378451',
 '379641',
 '380016',
 '380130',
 '381141',
 '381196',
 '381855',
 '382003',
 '382132',
 '382202',
 '382436',
 '383034',
 '383122',
 '383338',
 '384127',
 '384417',
 '384882',
 '384929',
 '385650',
 '385881',
 '385933',
 '386140',
 '386931',
 '387100',
 '387460',
 '387462',
 '387515',
 '387693',
 '388646',
 '388763',
 '389107',
 '389117',
 '389118',
 '389267',
 '389472',
 '389521',
 '389607',
 '389652',
 '390070',
 '390089',
 '390096',
 '390243',
 '390494',
 '390825',
 '390943',
 '390967',
 '390968',
 '391036',
 '391130',
 '391139',
 '391319',
 '391362',
 '391365',
 '391528',
 '391634',
 '391833',
 '391957',
 '392040',
 '392041',
 '392186',
 '392203',
 '392218',
 '392391',
 '392763',
 '392766',
 '392824',
 '393012',
 '393099',
 '393101',
 '393172',
 '393177',
 '393445',
 '393520',
 '393522',
 '393528',
 '393607',
 '393609',
 '393759',
 '393840',
 '393844',
 '393859',
 '393885',
 '393913',
 '393939',
 '393995',
 '393999',
 '394210',
 '394211',
 '394372',
 '394467',
 '394468',
 '394563',
 '394657',
 '394663',
 '394845',
 '394997',
 '395094',
 '395129',
 '395152',
 '395228',
 '395361',
 '395369',
 '395462',
 '395511',
 '395563',
 '395627',
 '395898',
 '395991',
 '396044',
 '396105_0',
 '396133',
 '396135',
 '396152',
 '396166',
 '396182',
 '396326',
 '396412',
 '396488',
 '396491',
 '396492',
 '396564',
 '396567',
 '396607',
 '396708',
 '396728',
 '396827',
 '396829',
 '396833',
 '396903',
 '396907',
 '396950',
 '397032',
 '397034',
 '397130',
 '397264',
 '397306',
 '397312',
 '397418',
 '397419',
 '397427',
 '397525',
 '397933',
 '397946',
 '398073_1',
 '398074',
 '398141',
 '398181',
 '398203',
 '398218',
 '398220',
 '398331',
 '398333',
 '398447',
 '398481',
 '398574',
 '398781',
 '398838',
 '398889',
 '399009',
 '399072',
 '399074',
 '399083',
 '399399',
 '399501',
 '399535',
 '399544',
 '399650',
 '399711',
 '399712',
 '399724',
 '399775',
 '399778',
 '399803',
 '399997',
 '399999',
 '400067',
 '400069',
 '400124',
 '400154',
 '400182',
 '400233',
 '400240',
 '400248',
 '400250',
 '400254',
 '400288',
 '400289',
 '400290',
 '400347',
 '400355',
 '400395',
 '400471',
 '400478',
 '400481',
 '400484',
 '400556',
 '400675',
 '400919',
 '400963',
 '400975',
 '400976',
 '400977',
 '401014',
 '401019',
 '401024',
 '401035',
 '401064',
 '401115',
 '401216',
 '401217',
 '401232',
 '401249',
 '401351',
 '401353',
 '401354',
 '401383',
 '401485',
 '401486',
 '401487',
 '401691',
 '401702',
 '401727',
 '401728',
 '401731',
 '401736',
 '41437-jenny-die-vergangenheit-hat-ti',
 '41446-kruemel-traechtige-kleine-huen',
 '41453-nera-ein-grosses-hundemaedel-s',
 '41487-daniel-stattlicher-hund-sucht-',
 '52251-aldo-eine-junge-fellnase',
 '52363-mia-sucht-ein-ruhiges-zuhause',
 '52592-viento-grazile-schwarze-schoen',
 '52665-trompy-ruhig-geduldig-und-frie',
 '53115-frodo-ein-netter-junghund',
 '53123-buba-ruhiger-kuscheliger-bursc',
 '53209-aurka-lernwilliger-liebenswert',
 '53212-soleil-wunderhuebsche-aktive-m',
 '53213-sam-treue-seele-liebt-lange-sp',
 '53401-danko-lernwilliger-huebscher-r',
 '53402-dora-wartet-schone-viel-zu-lan',
 '53403-ivan-idealer-wegbegleiter',
 '53528-notfall-huendin-mischa-eine-un',
 '53615-fuchur-mix-ruede-ca-1-3-jahre-',
 '53666-olga-warmes-koerbchen-fuer-olg',
 '53667-negrut-notfall-sucht-liebevoll',
 '53673-donald-wuenscht-sich-ein-liebe',
 '53819-paule-sucht-geduldige-und-beso',
 '54133-ciara-eine-schmusige-fellnase',
 '69069-intelligenter-aktiver-trump-m-',
 '69070-zauberhafte-liebe-zoya-w-6-j-s',
 '69071-phantastischer-wundervoller-ve',
 '69072-phantastischer-zauberhafter-vi',
 '69076-claire',
 '69079-bezaubernder-wunderschoener-za',
 '69080-phantastischer-bildschoener-zs',
 '69081-bildschoener-bezaubernder-zico',
 '69082-phantastischer-sanfter-szibi-m',
 '69084-kentucky-geb-ca-03-2017-maennl',
 '69085-milow-geb-ca-06-2016-maennlich',
 '69090-greta-geb-ca-12-2016-weiblich-',
 '69119-bildschoene-wundervolle-sissy-',
 '69120-wunderschoener-entzueckender-w',
 '69121-wundervolle-zauberhafte-zaya-w',
 '69126-bildschoene-zauberhafte-laila-',
 '69127-zauberhafte-wundervolle-lucy-w',
 '69128-bildschoene-zauberhafte-linda-',
 '69135-txano-moechte-sein-koefferchen',
 '69136-hugo-boss-geb-ca-12-2014-maenn',
 '69137-cora-w-kastr-staffordshire-bul',
 '69138-kusu-m-podenco-geb-ca-7-2018-s',
 '69139-princesa-w-kastr-mischling-geb',
 '69140-peque-m-podenco-geb-09-2016-ca',
 '69141-fiume-geb-ca-06-2017-weiblich-',
 '69143-igor-m-podenco-geb-ca-2017-ca-',
 '69144-africa-w-mischling-geb-10-2017',
 '69145-mina-w-dt-schaeferhund-geb-ca-',
 '69154-julie-w-schaeferhund-mix-geb-0',
 '69159-itza-w-mischling-geb-06-2017-c',
 '69163-brandy-m-misching-geb-01-2016-',
 '69165-nilo-m-bodeguero-geb-11-2017-c',
 '69168-sancho-m-kastr-mischling-ca-50',
 '69170-draven-m-mischling-geb-02-2018',
 '69171-chico-m-malinois-geb-05-2017-c',
 '69173-rio-m-mischling-geb-05-2016-ca',
 '69174-jupiter-m-mischling-geb-09-201',
 '69175-jimena-w-podenco-geb-ca-2012-2',
 '69176-notfall-havivi-m-mischling-geb',
 '69177-kiko-m-podenco-mix-geb-04-2018',
 '69181-pancho-negro-m-kastr-mischling',
 '69182-mali-w-kastr-malinois-geb-ca-2',
 '69183-darwin-m-mischling-geb-01-2017',
 '69188-copo-m-labrador-mix-geb-ca-201',
 '69192-ryo-m-kastr-mischling-geb-2016',
 '69195-sanda-w-kastr-malinois-geb-01-',
 '69196-botin-m-kastr-jagdterrier-mix-',
 '69213-wundervolle-sehr-liebe-afonya-',
 '69215-wunderschoener-gelehriger-aure',
 '69216-bildschoene-wundervolle-bodza-',
 '69218-wundervoller-sehr-lieber-boton',
 '69219-wundervolle-bildschoene-bolhas',
 '69220-phantastischer-bildschoener-cl',
 '69221-bezaubernde-bildschoene-daisy-',
 '69222-phantastischer-wunderschoener-',
 '69226-brownie-geb-ca-12-2016-weiblic',
 '69229-victoria-w-mischling-geb-01-20',
 '69230-canelo-m-ruede-mischling-geb-0',
 '69236-boby-geb-ca-12-2013-maennlich-',
 '69238-thyron-geb-ca-06-2016-maennlic',
 '69239-sofia-geb-ca-04-2018-weiblich-',
 '69266-anjo-freundlicher-aufgeschloss',
 '69267-merlin-5-wunderschoener-allerl',
 '69268-roy-2-lieber-schoener-vierbein',
 '69269-toby-7-allerliebster-terrier-m',
 '69271-owen-liebevoller-zutraulicher-',
 '69273-tigi-2-lieber-freundliches-hun',
 '69278-wunderschoener-diesel-m-6-j-su',
 '69279-sehr-menschenbezogene-fillis-w',
 '69280-sehr-menschenbezogene-franca-w',
 '69284-liebenswuerdiger-dankbarer-fin',
 '69285-sehr-menschenbezogene-jenna-w-',
 '69287-wundervoller-sonnenschein-enzo',
 '69291-wundervolle-herzige-fiona-w-6-',
 '69292-wundervolle-zauberhafte-haley-',
 '69294-liebreizende-bildschoene-fiona',
 '69297-andromeda-versteht-sich-gut-mi',
 '69298-verschmuster-gelehriger-ike-m-',
 '69300-sehr-menschenbezogene-melly-w-',
 '69302-wundervoller-lieber-rocco-m-3-',
 '69303-menschenbezogene-wundervolle-m',
 '69304-zauberhafter-rexi-m-2-j-sucht-',
 '69306-sehr-menschenbezogener-tyson-m',
 '69307-bildschoene-liebe-rya-w-1-j-su',
 '69308-menschenbezogener-sehr-lieber-',
 '69309-wundervoller-hinreissender-per',
 '69310-zauberhafter-menschenbezogener',
 '69311-peanut-geb-ca-04-2018-weiblich',
 '69313-sehr-menschenbezogene-liebe-ri',
 '69314-wunderschoener-sehr-lieber-noa',
 '69316-verschmuste-sehr-liebe-nala-w-',
 '69318-sehr-menschenbezogene-scarlett',
 '69320-verschmuster-lieber-lennox-m-3',
 '69321-sehr-menschenbezogener-nash-m-',
 '69369-powerhuendin-auf-drei-beinen-k',
 '69370-douglas-anhaenglich-wartet-seh',
 '69385-liebevollen-platz-fuer-unseren',
 '69401-kenzo-m-mischling-geb-05-2015-',
 '69403-punto-m-mischling-geb-04-2015-',
 '69405-bianca-w-mischling-geb-01-2017',
 '69407-rudy-m-mischling-geb-05-2015-c',
 '69408-jara-w-podenco-geb-ca-2015-ca-',
 '69409-roky-m-mischling-geb-ca-2016-c',
 '69410-hugo-m-engl-bulldogge-geb-07-2',
 '69411-pirata-m-mischling-geb-ca-2008',
 '69412-selva-w-mischling-geb-10-2017-',
 '69413-pau-w-mischling-geb-01-2010-ca',
 '69414-mario-m-mischling-geb-02-2014-',
 '69415-zipi-m-mischling-geb-01-2018-c',
 '69419-notfall-candy-warum-habt-ihr-d',
 '69424-bitte-schenkt-carlos-euer-herz',
 '69427-zic-geb-ca-08-2018-maennlich-n',
 '69439-reserviert-diamond-geb-ca-04-2',
 '69476-nala-sucht-dich',
 '69483-masni-3-freundliche-junge-huen',
 '69488-berny-unkomplizierter-wegbegle',
 '69490-emely-sanfte-schoenheit',
 '69503-notfall-ganga-wie-lange-muss-s',
 '69506-conny-sucht-aktives-zu-hause',
 '69507-renata-angefragt',
 '69512-bertin-lieb-folgsam-anhaenglic',
 '69530-anni-ruhige-sensible-dackel-mi',
 '69531-mike-wahre-schoenheit-kommt-au',
 '69533-ringo-11-jahre-warten-sind-gen',
 '69540-spike-geb-ca-05-2016-maennlich',
 '69541-penelope-geb-ca-05-2018-weibli',
 '69542-jonah-geb-ca-02-2018-maennlich',
 '69553-cicca-geb-ca-03-2018-weiblich-',
 '69572-flo-die-gewitzte',
 '69581-loba-eine-freundliche-menschen',
 '69582-scherie',
 '69583-drago-kinderlieb-katzenfreundl',
 '69589-pina-vom-besitzer-im-stich-gel',
 '69591-marco-aktiver-und-folgsamer-ru',
 '69592-cherry-aktiver-sonnenschein',
 '69593-linet-w-mischling-geb-ca-2016-',
 '69594-reserviert-pjedro-geb-ca-09-20',
 '69597-noel-hat-sich-sein-grosses-her',
 '69598-carlotta-moechte-gerne-sesshaf',
 '69602-riesenschnauzermischlingswelpe',
 '69607-copito-lustiger-mischlingshund',
 '69632-hektor-geb-ca-10-2015-maennlic',
 '69633-reserviert-wilma-geb-ca-01-201',
 '69636-green-ist-zu-allem-bereit',
 '69639-kitty-aktive-familie-gesucht',
 '69640-slash-froehlich-und-schlau',
 '69642-otello-menschen-mit-hundeerfah',
 '69652-nike',
 '69656-bobby-mix-ruede-ca-12-wochen-a',
 '69657-budderball-mix-ruede-ca-12-woc',
 '69658-fritzi-mix-ruede-ca-12-wochen-',
 '69659-gracie-mix-huendin-ca-12-woche',
 '69661-vega-mix-ruede-ca-12-wochen-al',
 '69666-max-ein-froehlicher-geselle',
 '69702-ninjo-geb-ca-jan-2018-maennlic',
 '69703-baron-geb-ca-2010-maennlich',
 '69707-lana-moechte-endlich-eine-lieb',
 '69709-robby-kleiner-schwarzer-diaman',
 '69710-akio-geb-ca-2013-maennlich',
 '69711-naira-geb-ca-juli-2018-weiblic',
 '69712-freya-geb-ca-2016-weiblich',
 '69713-billa-geb-ca-2016-weiblich-thu',
 '69714-maya-geb-ca-2008-weiblich-thur',
 '69757-yuca-ein-ganz-armer-tropf-verl',
 '69759-kesha-herzlos-ausrangiert',
 '69761-dina-endlich-liebe-und-geborge',
 '69768-charles-der-geniesser-mit-pfup',
 '69779-avi-verspieltes-neugieriges-hu',
 '69780-ariva-kontaktfreudiges-aufgewe',
 '69786-wunderschoener-verschmuster-ne',
 '69787-ago-5-suesse-aufgestellte-huen',
 '69789-bildschoene-bezaubernde-gwen-6',
 '69794-bobik-ca-4-5-j-05-2014-ca-48-c',
 '69797-felix-ca-6-j-09-2012-ca-49-cm-',
 '69800-funia-ca-4-j-02-2015-ca-42-cm-',
 '69801-sheela-ca-12-j-12-2006-ca-62cm',
 '69802-hinreissender-bambus-m-2-5-j-s',
 '69803-bildschoene-wundervolle-frida-',
 '69809-amulett-der-schmusbaer',
 '69814-jack-der-ruhige-sanfte-boy',
 '69816-lati-m-mischling-geb-11-2017-c',
 '69817-lora-ein-leben-an-der-kette',
 '69824-flora-2019-wird-dein-gluecksja',
 '69826-prisca-verliert-ihr-zuhause',
 '69828-milka-geb-ca-06-2017-weiblich-',
 '69829-schari-geb-ca-06-2016-maennlic',
 '69830-nala-geb-ca-06-2017-weiblich-k',
 '69833-kocos-4-aufgestellte-suesse-hu',
 '69835-jodi-3-freundlicher-aufgeschlo',
 '69840-kalay-geb-ca-12-2015-maennlich',
 '69841-maybel-geb-ca-12-2016-weiblich',
 '69862-liebenswerte-herzige-leila-w-1',
 '69863-bildschoener-herziger-denny-m-',
 '69870-entzueckende-wunderschoene-san',
 '69872-basco-ca-1-5-j-03-2015-ca-55-c',
 '69874-moira-ca-3-j-12-2015-ca-49-cm-',
 '69875-santiago-ca-6-j-12-2012-ca-57-',
 '69877-tenor-5-j-09-2013-ca-55-cm-23-',
 '69880-diana-ca-5-5-j-03-2013-ca-55-c',
 '69881-gino-ca-3-j-10-2015-ca-45-cm-m',
 '69882-julia-ca-2-j-09-2016-ca-50-cm-',
 '69884-tamino-der-ideale-partner-fuer',
 '69891-wundervolle-phantastische-para',
 '69892-verschmuster-furchtloser-strup',
 '69893-liebenswerte-herzige-kavics-w-',
 '69898-brody',
 '69901-suetike-sucht-warme-kuscheleck',
 '69902-schuechtern-aber-super-lieb-la',
 '69910-nelly-unser-kleiner-wirbelwind',
 '69920-monty-anhaenglicher-mischlings',
 '69931-richy-total-verzweifelt',
 '69959-kim-eine-liebenswerte-fellnase',
 '69964-kate-eine-liebenswerte-fellnas',
 '69967-kourtney-eine-liebenswerte-fel',
 '69968-karla-eine-l-iebenswerte-felln',
 '69969-golden-retriever-to-good-home',
 '69970-niebla-w-kastr-rafeiro-do-alen',
 '69971-kevin-eine-liebenwerte-fellnas',
 '69974-frodo-geb-ca-05-2018-maennlich',
 '69975-gipsy-ist-eine-hand-voll-gluec',
 '69976-suesser-aber-noch-etwas-schuec',
 '69977-die-suesse-froehliche-galga-le',
 '69980-lady-suesse-maus',
 '69981-rusty-ist-auf-der-suche-nach-s',
 '69982-peppone-megasuesser-fratz',
 '69983-joschi-megasuesser-fratz',
 '69985-hope-megasuesse-maus',
 '69986-wotan-sucht-aktive-leute',
 '69990-nero-sehnt-sich-so-sehr-nach-e',
 '69991-artus-sucht-einfuehlsame-mensc',
 '69999-fido-kleiner-prinz',
 '70002-ebba-perfekte-begleiterin-fuer',
 '70003-calippo-jogt-gerne',
 '70005-lotte-sucht-nach-dir',
 '70009-lizzy-geb-ca-10-2016-weiblich-',
 '70010-bandito-geb-ca-05-2018-maennli',
 '70011-sancho-5-jahre-gemuetlicher-hu',
 '70018-dulce-vertraegliche-und-schoen',
 '70019-conde-im-tierheim-gelandet-wei',
 '70020-dino-vertraeglicher-und-huebsc',
 '70021-mama-laura-wartet-schon-so-lan',
 '70022-jaguar-toller-und-vertraeglich',
 '70023-lola-geduldige-und-hundeerfahr',
 '70024-polo-freundlicher-vertraeglich',
 '70027-blanka-ca-2-5-j-06-2016-ca-50-',
 '70028-kaiko-ca-6-5-j-05-2012-ca-50-c',
 '70029-kora-ca-3-j-12-2015-ca-45-cm-w',
 '70030-reggie-ca-10-5-j-06-2008-ca-69',
 '70031-ronja-ca-1-5-j-04-2017-ca-47-c',
 '70032-karol-ca-5-j-09-2013-ca-71-cm-',
 '70033-pepper-ca-1-j-10-2017-ca-51-cm',
 '70036-nico-geb-ca-05-2018-maennlich-',
 '70038-daira-die-anhaengliche-mini-sc',
 '70040-django-geb-ca-05-2018-maennlic',
 '70042-abel-lieber-netter-freundliche',
 '70045-rolo-m-pitbull-mix-geb-ca-7-20',
 '70046-abbey-geb-ca-05-2018-weiblich-',
 '70053-italo-du-armer-tropf-wer-schen',
 '70054-raja-ist-reserviert',
 '70061-veroniki',
 '70066-owen-lieber-oldy-sucht-zuhause',
 '70072-nora-w-kastr-mischling-geb-ca-',
 '70073-noa-w-mischling-geb-01-2013-ca',
 '70074-robin-m-malinois-mix-geb-01-20',
 '70075-bruno-m-geb-01-2013-rafeiro-do',
 '70076-rafeiro-do-alentejo-mix',
 '70077-brisa-w-mischling-geb-01-2013-',
 '70078-nacho-m-mischling-geb-12-2016-',
 '70079-troll-m-mischling-geb-01-2017-',
 '70109-jaxon-vierbeiner-mit-grossem-h',
 '70111-wer-wuschelhunde-mag-wird-chew',
 '70114-bist-du-urmels-mensch-sein-beg',
 '70125-besonderer-hund-sucht-besonder',
 '70127-pluti-gute-laune-garantiert',
 '70128-negro-liebenswerter-aelterer-p',
 '70129-chaplin-treue-seele',
 '70133-ali-w-mischling-geb-08-2018-ca',
 '70134-lia-w-mischling-geb-11-2013-ca',
 '70135-mili-w-mischling-geb-03-2018-c',
 '70136-pili-w-mischling-geb-03-2018-c',
 '70137-santos-der-ideale-familienhund',
 '70141-nyla-megasuesse-biene',
 '70142-zorro-aktives-kerlchen',
 '70143-nando-megasuesser-fratz',
 '70144-rico-megasuesser-fratz',
 '70146-sonja-suesse-wuschelmaus',
 '70159-dora-alles-wird-gut',
 '70161-mary-grosse-lady-mit-noch-groe',
 '70165-dama-w-labrador-geb-ss3-2012-c',
 '70166-die-schoene-shaky-sucht-eine-f',
 '70167-nala-sucht-eine-familie',
 '70168-eleganter-mischlingshund-ken-s',
 '70169-zora-sucht-eine-familie',
 '70170-die-kleine-bella-sucht-ein-koe',
 '70172-der-kleine-bobby-sucht-eine-fa',
 '70173-nerina-sucht-eine-familie',
 '70174-judy-ist-ein-ganz-reizende-kle',
 '70176-zuckerschnute-airi-wickelt-ein',
 '70177-sebastien-sucht-ein-home-for-e',
 '70178-sportskanone-rufus-hat-so-viel',
 '70179-knutschkugel-flo-sucht-eine-fa',
 '70180-der-lustige-remi-sucht-eine-fa',
 '70181-zeus-sucht-eine-familie',
 '70182-april-sucht-noch-eine-familie',
 '70188-verspielter-huebscher-mischl-r',
 '70189-baloo-m-rafeiro-do-alelentejo-',
 '70190-luar-w-mischling-geb-ca-09-201',
 '70191-munay-w-mischling-geb-09-2015-',
 '70192-asia-w-deutscher-schaeferhund-',
 '70193-lana-w-mischling-geb-ca-2011-2',
 '70194-juanita-w-mischling-geb-01-201',
 '70195-martin-m-staffordshire-terrier',
 '70196-alicia-w-mischling-geb-01-2014',
 '70197-azucena-w-mischling-geb-ca-06-',
 '70204-troylo-ein-froehlicher-kleiner',
 '70206-edith-sonnenschein-sucht-traum',
 '70207-clark-notfall-hofft-nicht-mehr',
 '70209-verschmuster-menschenbezogener',
 '70212-sehr-menschenbezogene-bogi-w-3',
 '70213-hinreissender-herziger-bundi-m',
 '70214-bildschoener-mason-m-1-j-sucht',
 '70215-phantastische-herzige-zsuzsa-w',
 '70216-wundervoller-zauberhafter-flor',
 '70217-dean-lieber-sanfter-9-monate-a',
 '70218-hinreissender-zauberhafter-pep',
 '70219-baro-5-wunderschoener-allerlie',
 '70220-zotya-3-lieber-freundlicher-hu',
 '70221-hera-2-freundliche-treue-staff',
 '70231-mattie-moechte-noch-einmal-lie',
 '70240-liebreizende-bildschoene-sally',
 '70247-kleiner-entzueckender-prince-m',
 '70249-kleine-bezaubernde-pola-w-2-5-',
 '70250-wer-hat-ein-herz-fuer-unseren-',
 '70252-charly-1-jahr-collie-husky-mix',
 '70255-drinend-wer-erloest-lina-von-i',
 '70258-bildschoener-entzueckender-rud',
 '70260-desy-anhaenglich-sucht-liebe-m',
 '70261-topper-kleiner-hund-grosses-he',
 '70277-wunderschoene-tanja-w-1-j-such',
 '70286-bildschoener-menschenbezogener',
 '70296-wunderschoener-herziger-michae',
 '70299-hinreissender-wundervoller-the',
 '70300-einzigartige-menschenbezogene-',
 '70303-zuckersuesser-kleiner-doemper-',
 '70304-wunderschoene-liebe-tracy-w-8-',
 '70306-traurig-blickender-lieber-bing',
 '70310-der-sportliche-rex',
 '70317-nias-leidet-und-baut-immer-meh',
 '70324-balu-m-mischling-geb-10-2013-c',
 '70325-irina-w-mischling-geb-11-2017-',
 '70326-perla-w-galgo-geb-01-2018-ca-6',
 '70335-tala-geb-ca-08-2018-weiblich-n',
 '70340-bildschoener-janis-m-2-j-sucht',
 '70341-vertrauensvolle-herzige-franka',
 '70344-bildschoener-lieber-jackson-m-',
 '70345-junis-braucht-keine-action-er-',
 '70346-liebevollen-gnadenplatz-fuer-a',
 '70347-zauberhafte-wundervolle-janka-',
 '70348-nando-unser-zuckersuesser-aufg',
 '70349-verschmuster-herziger-big-mac-',
 '70350-wunderschoener-toller-diego-m-',
 '70353-huebscher-schaeferh-bub-sucht-',
 '70360-bimba-ca-5-mte-08-2018-ca-35-c',
 '70361-cholo-ca-2-5-j-05-2016-ca-48-c',
 '70362-elisa-ca-6-j-02-2013-ca-57-cm-',
 '70363-lili-ca-3-j-11-2015-ca-44-cm-c',
 '70364-lisa-ca-9-j-01-2010-ca-52-cm-c',
 '70365-lukas-ca-1-j-08-2017-ca-42-cm-',
 '70366-luna-ca-6-j-02-2013-ca-50-cm-1',
 '70367-mirna-ca-8-j-01-2011-ca-55-cm-',
 '70368-numa-ca-9-mte-03-2018-ca-50-cm',
 '70369-paco-ca-12-j-02-2007-ca-57-cm-',
 '70370-rolo-ca-2-j-11-2016-ca-52-cm-c',
 '70371-rubio-ca-1-5j-07-2017-ca-39-cm',
 '70372-siena-ca-2-j-08-2016-ca-46-cm-',
 '70373-titan-ca-5-j-12-2013-ca-35-cm-',
 '70374-willy-ca-5-j-12-2013-ca-30-cm-',
 '70381-freundlicher-braver-mischl-bub',
 '70382-fufu-ca-3-j-10-2015-ca-52-cm-3',

In [38]:
len(foldernames)

1447

In [ ]:
for i in len(foldernames):

In [32]:
for f in filenames:
    c = 0
    s = f.find('.',0)
    while s >= 0:
        s = f.find('.',s+1)
        c += 1
    if c > 2:
        print(f)

Angie.Angie17.jpeg.jpg
B.Atis.B.Atis1.jpg
B.Atis.B.Atis10.jpg
B.Atis.B.Atis11.jpg
B.Atis.B.Atis12.jpg
B.Atis.B.Atis13.jpg
B.Atis.B.Atis2.jpg
B.Atis.B.Atis4.jpg
B.Atis.B.Atis5.jpg
B.Atis.B.Atis6.jpg
B.Atis.B.Atis7.jpg
B.Atis.B.Atis9.jpg
B.Dömpi.B.Doempi1.jpg
B.Dömpi.B.Doempi10.jpg
B.Dömpi.B.Doempi11.jpg
B.Dömpi.B.Doempi12.jpg
B.Dömpi.B.Doempi14.jpg
B.Dömpi.B.Doempi15.jpg
B.Dömpi.B.Doempi16.jpg
B.Dömpi.B.Doempi17.jpg
B.Dömpi.B.Doempi18.jpg
B.Dömpi.B.Doempi19.jpg
B.Dömpi.B.Doempi20.jpg
B.Dömpi.B.Doempi21.jpg
B.Dömpi.B.Doempi22.jpg
B.Dömpi.B.Doempi23.jpg
B.Dömpi.B.Doempi24.jpg
B.Dömpi.B.Doempi5.jpg
B.Dömpi.B.Doempi7.jpg
B.Dömpi.B.Doempi8.jpg
B.Lukas.B.Lukas1.jpg
B.Lukas.B.Lukas10.jpg
B.Lukas.B.Lukas2.jpg
B.Lukas.B.Lukas3.jpg
B.Lukas.B.Lukas4.jpg
B.Lukas.B.Lukas5.jpg
B.Lukas.B.Lukas6.jpg
B.Lukas.B.Lukas7.jpg
B.Lukas.B.Lukas8.jpg
B.Lukas.B.Lukas9.jpg
Barokk.Barokk10.jpeg.jpg
Basso.Basso7.jpeg.jpg
Betyar-3.Betyar-3-8.jpeg.jpg
Brenda.Brenda1..jpg
Caspio.Caspio8.jpeg.jpg
Diva-4.Diva-4-8..jpg
dog10.2013-07-04 12.29.51.jpg
dog10.2017-02-19 15.44.20-1.jpg
dog10.2017-02-19 16.45.50.jpg
dog11.2013-06-25 15.15.01.jpg
dog11.70. Geb. Claus 093.jpg
dog11.70. Geb. Claus 123.jpg
dog11.70. Geb. Claus 128.jpg
dog11.70. Geb. Claus 130.jpg
dog12.2013-07-04 14.40.34.jpg
dog12.2013-07-04 14.40.49.jpg
dog12.70. Geb. Claus 128 - Copie.jpg
dog12.70. Geb. Claus 130 - Copie.jpg
dog9.2014-10-3.-5. (151 von 281).jpg
dog9.2014-10-3.-5. (152 von 281).jpg
dog9.2014-10-3.-5. (179 von 281).jpg
Dömpi-2.Doempi-2-5..jpg
Elinor.Elinor10.jpeg.jpg
Furia.Furia10.jpeg.jpg
Hello.Hello3..jpg
Jando.Jando5.jpeg.jpg
Joli-3.Joli-3-5.jpeg.jpg
Katus.Katus7..jpg
Kismacko.Kismacko14..jpg
Kismacko.Kismacko17.1.jpg
Kismacko.Kismacko21..jpg
Kismacko.Kismacko24..jpg
Luigi-4.Luigi-4-6.jpeg.jpg
Mario-7.Mario-7-8.jpeg.jpg
Morris-2.Morris-2-15..jpg
Morris-2.Morris-2-16..jpg
Morris-2.Morris-2-2..jpg
Morris-2.Morris-2-27.jpeg.jpg
Morris-2.Morris-2-29..jpg
Morris-2.Morris-2-30.jpeg.jpg
Morris-2.Morris-2-7.1.jpg
Morzsi-6.Morzsi-6-10..jpg
Morzsi-6.Morzsi-6-5..jpg
Pali.Pali5..jpg
Pali.Pali6..jpg
Pimpi.Pimpi8.jpeg.jpg
Riley-2.Riley-2-9.jpeg.jpg
Ronja-2.Ronja-2-3..jpg
Ronja-2.Ronja-2-7.jpeg.jpg
Sam-9.Sam-9-10.jpeg.jpg
Siri-2.Siri-2-7.jpeg.jpg
Thanos.Thanos9.jpeg.jpg
Toby-7.Toby-7.1.jpg
Uxan.Uxan6.jpeg.jpg
Wenda.Wenda13..jpg
Wenda.Wenda2..jpg
Zeller.Zeller26..jpg
Zeno-4.Zeno-4-14.jpg.jpg
Zeno-4.Zeno-4-9.1.jpg
Zorro-5.Zorro-5-10.jpeg.jpg
Zorro-5.Zorro-5-6.jpeg.jpg
Zumba-2.Zumba-2-7.jpeg.jpg

In [17]:
filenames = df4["filename"]
for i in tqdm_notebook(range(len(filenames))):
    f = filenames[i]
    for s in range(len(f)):
        if f[s]=='.':
            if s > 1:
                break
    filenames[i] = f[s+1:]
filenames

HBox(children=(IntProgress(value=0, max=8698), HTML(value='')))

c:\users\guillaume\anaconda3\lib\site-packages\ipykernel_launcher.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy

0                272100.jpg
1              272100_0.jpg
2              272100_1.jpg
3              272100_2.jpg
4              272100_4.jpg
5              272100_5.jpg
6                272774.jpg
7             272774_0.jpeg
8              272774_0.jpg
9              272774_1.jpg
10             272774_2.jpg
11             272774_3.jpg
12              272986.jpeg
13               272986.jpg
14             272986_0.jpg
15             272986_1.jpg
16             272986_2.jpg
17             272986_5.jpg
18             272986_6.jpg
19              274575.jpeg
20               274575.jpg
21            274575_0.jpeg
22             274575_0.jpg
23             274575_1.jpg
24             274575_2.jpg
25             274575_3.jpg
26             274575_4.jpg
27             276562_0.jpg
28             276562_2.jpg
29             276562_3.jpg
               ...
8668         Zeusz-11-5.jpg
8669         Zeusz-11-6.jpg
8670         Zeusz-11-7.jpg
8671         Zeusz-11-8.jpg
8672          Zorro-5-1.jpg
8673          Zorro-5-2.jpg
8674          Zorro-5-3.jpg
8675          Zorro-5-4.jpg
8676     Zorro-5-6.jpeg.jpg
8677          Zorro-5-7.jpg
8678          Zorro-5-8.jpg
8679          Zorro-5-9.jpg
8680    Zorro-5-10.jpeg.jpg
8681         Zorro-5-20.jpg
8682          Zotya-3-1.jpg
8683          Zotya-3-2.jpg
8684          Zotya-3-3.jpg
8685          Zotya-3-4.jpg
8686          Zotya-3-5.jpg
8687            Zsu-2-1.jpg
8688            Zsu-2-2.jpg
8689            Zsu-2-3.jpg
8690            Zsu-2-4.jpg
8691            Zsu-2-5.jpg
8692          Zumba-2-2.jpg
8693          Zumba-2-3.jpg
8694          Zumba-2-4.jpg
8695          Zumba-2-5.jpg
8696          Zumba-2-6.jpg
8697          Zumba-2-9.jpg
Name: filename, Length: 8698, dtype: object

In [18]:
len(filenames)

8698

In [19]:
import numpy as np

In [20]:
test = np.array(filenames)

In [21]:
filenames[0] in test

True

In [24]:
to_remove = []
c = 0
for root,dirs,files in os.walk("../../data/dogfacenet/images_2/"):
    for f in files:
        c += 1
        if not f in test: 
            to_remove += [f]
            
print(len(to_remove))
print(c)
print(c-len(to_remove))

5637
11172
5535

In [60]:
for root,dirs,files in os.walk("../../data/dogfacenet/images/"):
    for f in files:
        c += 1
        if not f in test: 
            os.remove(root+'/'+f)